/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/events/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetJobEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PauseJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResumeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RetryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SendJobMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workitems/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetJobDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/permissions/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnswerPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPermissionRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RevokePermissionRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIdeas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIdea"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workitems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorkItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workitems/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorkItemTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workitems/{id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorkItemConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/antiforgery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAntiforgeryToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AntiforgeryTokenVm: {
            token: string;
        };
        /** @description Read-only settings. Explicit fields only: tokens, keys and secrets have no way in. */
        ConfigVm: {
            tag: string;
            claimTag: string;
            /** Format: int64 */
            pollIntervalSeconds: number;
            /** Format: int32 */
            maxConcurrent: number;
            requirePlanApproval: boolean;
            reviewLoop: boolean;
            handoff: boolean;
            repositories: components["schemas"]["RepositoryVm"][];
            messagingProviders: string[];
        };
        /** @description A conversation line: `direction` is `out` (agentd) or `in` (a developer's reply or command, by `author`). */
        ConversationEntryVm: {
            /** Format: date-time */
            at: string;
            /** Format: int64 */
            jobId: null | number;
            direction: string;
            kind: string;
            text: string;
            provider: null | string;
            author: null | string;
            status: null | string;
            error: null | string;
        };
        ConversationVm: {
            provider: string;
            /** Format: uri */
            link: null | string;
            open: boolean;
        };
        DashboardVm: {
            stats: {
                [key: string]: number;
            };
            activeJobs: components["schemas"]["JobSummaryVm"][];
            /** Format: int64 */
            latestSeq: number;
        };
        /** @description A job's changes; `unifiedDiff` is null when `truncated` (over 2 MB), leaving the file list. */
        DiffVm: {
            baseRef: string;
            headRef: string;
            files: string[];
            unifiedDiff: null | string;
            truncated: boolean;
        };
        EstimateVm: {
            /** Format: int32 */
            minutes: number;
            /** Format: int32 */
            usagePercent: number;
            /** Format: double */
            usageAtPlan: null | number;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            approvedAt: null | string;
        };
        EventPageVm: {
            events: components["schemas"]["EventVm"][];
            /** Format: int64 */
            oldestSeq: null | number;
            /** Format: int64 */
            newestSeq: null | number;
            hasMore: boolean;
        };
        /** @description One event; the payload is JSON passed through (it was redacted when stored). */
        EventVm: {
            /** Format: int64 */
            seq: number;
            /** Format: int64 */
            jobId: null | number;
            /** Format: date-time */
            ts: string;
            type: string;
            payload: components["schemas"]["JsonElement"];
        };
        /** @description A history page; `totalCapped` means "more than `total`" (shown as 10,000+). */
        HistoryPageVm: {
            items: components["schemas"]["JobSummaryVm"][];
            /** Format: int64 */
            total: number;
            totalCapped: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        IdeaDetailVm: {
            idea: components["schemas"]["IdeaSummaryVm"];
            drafts: components["schemas"]["WorkItemDraftVm"][];
            messages: components["schemas"]["IdeaMessageVm"][];
        };
        /** @description One message of the idea's conversation: `in` from a person, `out` from the agent (Markdown). */
        IdeaMessageVm: {
            direction: string;
            author: string;
            text: string;
            /** Format: date-time */
            at: string;
        };
        IdeaSummaryVm: {
            /** Format: int64 */
            id: number;
            repo: string;
            title: string;
            author: string;
            status: string;
            model: null | string;
            effort: null | string;
            /** Format: int32 */
            drafts: number;
            createdWorkItems: number[];
            /** Format: int32 */
            messages: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobDetailVm: {
            job: components["schemas"]["JobSummaryVm"];
            /** Format: int32 */
            attempt: number;
            /** Format: int32 */
            resumeCount: number;
            /** Format: int32 */
            pendingMessages: number;
            estimate: null | components["schemas"]["EstimateVm"];
            lastActivity: null | string;
            /** Format: date-time */
            lastActivityAt: null | string;
            usage: null | components["schemas"]["UsageVm"];
            conversations: components["schemas"]["ConversationVm"][];
            permissions: components["schemas"]["PermissionRequestVm"][];
        };
        /** @description A running job's agent process tree (CPU is percent of one core) and its worktree size. */
        JobResourcesVm: {
            /** Format: int64 */
            jobId: number;
            /** Format: double */
            cpuPercent: number;
            /** Format: int64 */
            memoryBytes: number;
            /** Format: int64 */
            worktreeBytes: null | number;
            /** Format: date-time */
            at: string;
        };
        /** @description A job row (dashboard, history). State and statuses are strings for the UI. */
        JobSummaryVm: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            workItemId: number;
            title: string;
            repo: string;
            branch: null | string;
            state: string;
            phase: null | string;
            /** Format: date-time */
            startedAt: string;
            /** Format: int64 */
            elapsedSeconds: number;
            prUrl: null | string;
            /** Format: date-time */
            waitingSince: null | string;
            planStatus: string;
            handoff: string;
            /** Format: int32 */
            fixRounds: number;
            lastError: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: int32 */
            pendingPermissions: number;
        };
        JsonElement: unknown;
        /** @description The machine agentd runs on (null fields: not sampled, e.g. off Linux). */
        MachineVm: {
            /** Format: double */
            cpuPercent: number;
            /** Format: int64 */
            memoryTotal: number;
            /** Format: int64 */
            memoryAvailable: number;
            /** Format: int64 */
            diskTotal: number;
            /** Format: int64 */
            diskFree: number;
            lowMemory: boolean;
            lowDisk: boolean;
            /** Format: date-time */
            at: string;
        };
        MessageAcceptedVm: {
            outcome: string;
        };
        MessageRequest: {
            text: string;
        };
        PermissionAnswerRequest: {
            choice: string;
        };
        /** @description A tool call outside the agent's allowlist, waiting for a person (`ruleKeys`: what "allow for this job / always" remembers). */
        PermissionRequestVm: {
            /** Format: int64 */
            id: number;
            tool: string;
            summary: string;
            ruleKeys: string[];
            /** Format: date-time */
            requestedAt: string;
        };
        /** @description A remembered approval; `jobId` null means every job of the repository. */
        PermissionRuleVm: {
            /** Format: int64 */
            id: number;
            repo: string;
            /** Format: int64 */
            jobId: null | number;
            ruleKey: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        PullRequestLinkVm: {
            /** Format: int64 */
            jobId: number;
            url: string;
        };
        RepositoryVm: {
            name: string;
            organization: string;
            project: string;
            baseBranch: string;
        };
        ResourcesVm: {
            machine: null | components["schemas"]["MachineVm"];
            jobs: components["schemas"]["JobResourcesVm"][];
        };
        RunAcceptedVm: {
            /** Format: int64 */
            jobId: number;
        };
        UsageVm: {
            /** Format: double */
            fiveHour: null | number;
            /** Format: double */
            weekly: null | number;
            /** Format: date-time */
            resetsAt: null | string;
        };
        /** @description The signed-in user; in Mode None, `{ name: "local", roles: ["Admin"], provider: "local" }`. */
        UserVm: {
            name: string;
            roles: string[];
            provider: string;
        };
        /** @description A proposed work item; a task's `parent` is its story's index in the list. */
        WorkItemDraftVm: {
            type: string;
            title: string;
            description: null | string;
            acceptanceCriteria: null | string;
            /** Format: double */
            estimate: null | number;
            /** Format: int32 */
            parent: null | number;
            tags: string[];
        };
        /** @description One work item across its jobs (oldest first), with its PRs and chat threads (open or closed). */
        WorkItemVm: {
            /** Format: int32 */
            workItemId: number;
            title: string;
            repo: string;
            jobs: components["schemas"]["JobSummaryVm"][];
            pullRequests: components["schemas"]["PullRequestLinkVm"][];
            conversations: components["schemas"]["ConversationVm"][];
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastActivityAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardVm"];
                };
            };
        };
    };
    GetJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailVm"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetJobEvents: {
        parameters: {
            query?: {
                after?: number;
                before?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageVm"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetJobEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventVm"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchHistory: {
        parameters: {
            query?: {
                state?: string;
                repo?: string;
                q?: string;
                from?: string;
                to?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPageVm"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PauseJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ResumeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RetryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SendJobMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageAcceptedVm"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RunWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedVm"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetJobDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffVm"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVm"];
                };
            };
        };
    };
    GetResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcesVm"];
                };
            };
        };
    };
    AnswerPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["PermissionAnswerRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPermissionRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionRuleVm"][];
                };
            };
        };
    };
    RevokePermissionRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetIdeas: {
        parameters: {
            query?: {
                workItem?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdeaSummaryVm"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetIdea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdeaDetailVm"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemVm"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetWorkItemTimeline: {
        parameters: {
            query?: {
                after?: number;
                before?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageVm"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetWorkItemConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntryVm"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetAntiforgeryToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AntiforgeryTokenVm"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserVm"];
                };
            };
        };
    };
}
