using Agentd.Application.Abstractions;
using Agentd.Application.Events;
using Agentd.Application.Jobs;
using Agentd.Application.Messaging;
using Agentd.Application.Ports;
using Agentd.Application.Queries;
using Agentd.Application.Repositories;
using Agentd.Application.Users;
using Agentd.Domain.Common;
using Agentd.Domain.Jobs;
using Agentd.Domain.Jobs.ValueObjects;
using Agentd.Domain.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Agentd.Application;

public static class DependencyInjection
{
    /// <summary>Registers the use-case handlers. Ports are registered by Infrastructure; options by the Host.</summary>
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddSingleton<NoMatchNotices>();
        services.AddScoped<ICommandHandler<ClaimWorkItem, JobId>, ClaimWorkItemHandler>();
        services.AddScoped<ICommandHandler<PollWorkItems, int>, PollWorkItemsHandler>();
        services.AddScoped<ICommandHandler<StartNextJob, AgentRunRequest?>, StartNextJobHandler>();
        services.AddScoped<ICommandHandler<HandleAgentExit, JobState>, HandleAgentExitHandler>();
        services.AddScoped<ICommandHandler<RecordAgentOutput, long>, RecordAgentOutputHandler>();
        services.AddScoped<ICommandHandler<FinishWork, PullRequestRef>, FinishWorkHandler>();
        services.AddScoped<ICommandHandler<PublishPullRequest, PullRequestRef>, PublishPullRequestHandler>();
        services.AddScoped<ICommandHandler<CancelJob, Unit>, CancelJobHandler>();
        services.AddScoped<ICommandHandler<PauseJob, Unit>, PauseJobHandler>();
        services.AddScoped<ICommandHandler<ResumeJob, Unit>, ResumeJobHandler>();
        services.AddScoped<ICommandHandler<RecoverJobsOnStartup, RecoveryPlan>, RecoverJobsOnStartupHandler>();
        services.AddScoped<ICommandHandler<RetryDuePublishes, int>, RetryDuePublishesHandler>();
        services.AddSingleton<ProfileSessions>();
        services.AddSingleton<IStepAnnouncer, StepAnnouncer>();
        services.AddSingleton<JobDispatcher>();
        services.AddScoped<IQueryHandler<GetJobStatus, IReadOnlyList<JobStatusRow>>, GetJobStatusHandler>();
        services.AddScoped<IQueryHandler<GetDashboard, Dashboard>, GetDashboardHandler>();
        services.AddScoped<IQueryHandler<GetJob, JobDetail?>, GetJobHandler>();
        services.AddScoped<IQueryHandler<GetJobEvents, EventPage>, GetJobEventsHandler>();
        services.AddScoped<IQueryHandler<GetConfigSummary, ConfigSummary>, GetConfigSummaryHandler>();
        services.TryAddSingleton(TimeProvider.System);
        services.AddSingleton<Permissions.PermissionWaiter>();
        services.AddSingleton<Ideas.IdeaService>();
        services.AddSingleton<Jobs.JobFollowUps>();
        services.AddSingleton<Reviews.ReviewService>();
        services.AddSingleton<Reviews.ReviewSessionReviewer>();
        services.AddSingleton<Reviews.ReviewSessionAsks>();
        services.AddSingleton<Reviews.ReviewSessionService>();
        services.AddSingleton<Reviews.BranchReviews>();
        services.AddSingleton<Reviews.ReviewSessionFixer>();
        services.AddSingleton<Reviews.ReviewSessionSend>();
        services.AddSingleton<Chats.ChatService>();
        services.AddSingleton<AzureDevOps.AdoConnections>();
        services.AddSingleton<AzureDevOps.AdoActor>();
        services.AddSingleton<AzureDevOps.AdoUserTokens>();
        services.AddSingleton<AzureDevOps.AdoOnBehalf>();
        services.AddSingleton<Setup.SetupService>();
        services.AddScoped<ICommandHandler<Permissions.PermissionAsk, Permissions.PermissionDecision>, Permissions.PermissionAskHandler>();
        services.AddScoped<ICommandHandler<Permissions.PermissionAnswer, bool>, Permissions.PermissionAnswerHandler>();
        services.AddScoped<IQueryHandler<Permissions.GetPermissionRules, IReadOnlyList<Permissions.PermissionRule>>, Permissions.GetPermissionRulesHandler>();
        services.AddScoped<ICommandHandler<Permissions.RevokePermissionRule, Unit>, Permissions.RevokePermissionRuleHandler>();
        services.AddScoped<IQueryHandler<GetResources, ResourcesView>, GetResourcesHandler>();
        services.AddScoped<IQueryHandler<GetIdeas, IReadOnlyList<Ideas.IdeaSummary>>, GetIdeasHandler>();
        services.AddScoped<IQueryHandler<GetIdea, IdeaDetail?>, GetIdeaHandler>();
        services.AddScoped<IQueryHandler<GetWorkItem, WorkItemSummary?>, GetWorkItemHandler>();
        services.AddScoped<IQueryHandler<GetWorkItemTimeline, EventPage>, GetWorkItemTimelineHandler>();
        services.AddScoped<IQueryHandler<GetWorkItemConversation, IReadOnlyList<ConversationEntry>>, GetWorkItemConversationHandler>();
        services.AddScoped<IQueryHandler<GetJobEventDetail, AgentEventDto?>, GetJobEventDetailHandler>();
        services.AddScoped<IQueryHandler<SearchHistory, HistoryPage>, SearchHistoryHandler>();
        services.AddScoped<IQueryHandler<GetJobDiff, Result<BranchDiff>>, GetJobDiffHandler>();
        services.AddScoped<ICommandHandler<AddRepository, Repository>, AddRepositoryHandler>();
        services.AddScoped<ICommandHandler<RemoveRepository, Unit>, RemoveRepositoryHandler>();
        services.AddScoped<ICommandHandler<SeedRepositories, SeedResult>, SeedRepositoriesHandler>();
        services.AddScoped<ICommandHandler<SeedUsers, int>, SeedUsersHandler>();
        services.AddSingleton<ConversationTargetsResolver>();
        services.AddSingleton<IMessagingProviderRegistry, MessagingProviderRegistry>();
        services.AddScoped<MessagingService>();
        services.AddSingleton<OutboxDispatcher>();
        services.AddScoped<ICommandHandler<SubmitDeveloperMessage, DeveloperMessageOutcome>, SubmitDeveloperMessageHandler>();
        services.AddScoped<ICommandHandler<RetryJob, int>, RetryJobHandler>();
        services.AddScoped<ICommandHandler<AskDeveloper, Unit>, AskDeveloperHandler>();
        services.AddScoped<ICommandHandler<ReportProgress, Unit>, ReportProgressHandler>();
        services.AddScoped<ICommandHandler<ResumeJobTurn, AgentRunRequest?>, ResumeJobTurnHandler>();
        services.AddScoped<ICommandHandler<TakeDeveloperMessages, IReadOnlyList<string>>, TakeDeveloperMessagesHandler>();
        services.AddSingleton<JobActivity>();
        services.AddSingleton<IAgentActivitySink>(sp => sp.GetRequiredService<JobActivity>());
        services.AddScoped<ICommandHandler<SetPhase, Unit>, SetPhaseHandler>();
        services.AddScoped<ICommandHandler<SubmitPlan, PlanOutcome>, SubmitPlanHandler>();
        services.AddScoped<ICommandHandler<ReviewPullRequests, int>, ReviewPullRequestsHandler>();
        services.AddScoped<ICommandHandler<StartHandoff, Unit>, StartHandoffHandler>();
        services.AddScoped<ICommandHandler<ProposeKnowledge, Unit>, ProposeKnowledgeHandler>();
        services.AddScoped<ICommandHandler<RequestCloseOut, Unit>, RequestCloseOutHandler>();
        services.AddScoped<ICommandHandler<AnswerCloseOut, bool>, AnswerCloseOutHandler>();
        services.AddSingleton<HeartbeatState>();
        services.AddScoped<ICommandHandler<PostHeartbeats, int>, PostHeartbeatsHandler>();
        services.AddScoped<ICommandHandler<SweepWorktrees, int>, SweepWorktreesHandler>();
        services.AddScoped<ICommandHandler<CheckWaitingJobs, int>, CheckWaitingJobsHandler>();
        services.AddScoped<ChatCommands>();
        services.AddScoped<ICommandHandler<RepairConversations, int>, RepairConversationsHandler>();
        services.AddScoped<InboundMessageHandler>();
        services.AddScoped<IInboundMessageSink>(sp => sp.GetRequiredService<InboundMessageHandler>());
        return services;
    }
}
