<Project Sdk="MSTest.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Agentd.Host\Agentd.Host.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>
</Project>
